### PR TITLE
Fixes #1955, retrieve YouTube category without API

### LINKED ISSUE #1955: Unable to scorbble from Youtube
Scrobbling from youtube does nothing

### Expected behavior

Scrobble music from Youtube

### Current behavior

Absolutely nothing happens due to 403 youtube API error:
`youtube.js:210 GET https://www.googleapis.com/youtube/v3/videos?part=snippet&id=hSyfPujR5tg&key=%APIKEYHERE% 403`

```json
{
  "error": {
    "errors": [
      {
        "domain": "usageLimits",
        "reason": "dailyLimitExceeded",
        "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=265200169229",
        "extendedHelp": "https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=265200169229"
      }
    ],
    "code": 403,
    "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=265200169229"
  }
}
```

### Possible solution

add more API keys or make possiblity to setup own API keys

### Steps to reproduce (for bugs)

1. Visit any youtube music video page, i.e.: https://www.youtube.com/watch?v=cUbFzEMQ2F
2. Check console

### Steps for resolving the issue
-   [x] Reauthenticate on Last.fm
    
    
    
-   [x] Try to use unpacked extension from latest master
    
    
-   [x] Check other issues for duplicates

### Environment

-   Version used: `commit ed9a10eed71f38810cc4aad7ce8c2baef2718aa4 (HEAD -> master, tag: v2.16.0, origin/master, origin/HEAD)`
-   Browser name and version: Opera 60 `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36 OPR/60.0.3255.27`

### PR DESCRIPTION
**Pull request by stephanebruckert**
I suggest this solution to fix https://github.com/web-scrobbler/web-scrobbler/issues/1955 by getting the Youtube category from the page itself, instead of using the API to fetch the category.

Pros:

 - no need for the API anymore (scalable, no shared keys in the repo, no need to add more keys),
 - no need to translate "Music" or "Entertainment" in all languages, as we now look for a "Category ID" which is a YouTube channel: [Music `/channel/UC-9-kyTW8ZkZNDHQJ6FgpwQ`](https://www.youtube.com/channel/UC-9-kyTW8ZkZNDHQJ6FgpwQ) & [Entertainment `/channel/UCi-g4cjqGV7jvU8aeSuj0jQ`](https://www.youtube.com/channel/UCi-g4cjqGV7jvU8aeSuj0jQ)

Cons: 

 - (fixed) ~~this solution comes with a small glitch. Since we get the category from the "More" button and then hide it quickly using "Less", the more/less button will quickly appear and disappear when the page loads (for 100ms maybe).~~

Let me know what you think. In the meantime I am still trying to see if I can hide() the glitch in some way.

### CODE REVIEW

**Comment by stephanebruckert** [comment]
The more/less glitch looks like:
giphy
We can only see it we scroll to the bottom of the page when the page loads. Let me know if it should be improved.

Also the YouTube integration test is not passing on the CI (times out), but it passes on my machine. I am not sure where to look anymore. Any help would very much appreciated. 

Thanks

**Comment by stephanebruckert** [comment]
I pulled from master and it's all green now. Thanks @alexesprit 

Also I was able to fully hide the more/less glitch.

**Comment by alexesprit** [comment]
> (fixed) this solution comes with a small glitch. Since we get the category from the "More" button and then hide it quickly using "Less", the more/less button will quickly appear and disappear when the page loads (for 100ms maybe).

It's fixed for those who have English language selected.

**Comment by stephanebruckert** [comment]
Nice catch @alexesprit, thanks. I've committed your suggestions

**Comment by stephanebruckert** [comment]
This is ready to be merged

**Comment by alexesprit** [comment]
@stephanebruckert could you rebase to latest master, squash commits and force-push changes?

**Comment by stephanebruckert** [comment]
@alexesprit there are currently no conflicts. Would you be able to squash-merge the PR? https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests

**Comment by stephanebruckert** [comment]
Done.

**Comment by stephanebruckert** [comment]
@alexesprit when are we able to release this? It seems people are looking forward to scrobble from YouTube again

**Comment by alexesprit** [comment]
@stephanebruckert 

1. There's no ETA for releases.
2. If I merge this PR now, it won't be published immediately.
3. I tried to resolve the issue by asking for increase quota, and I'm waiting for response. I plan on merging this PR if they won't respond in one or two weeks (and I asked about two weeks ago).

**Comment by stephanebruckert** [comment]
Even if you manage to increase the API quota, wouldn't this PR still be the best alternative to retrieve the category?

**Pull request merged**
