### PR TITLE
Added Connectors for CBC Music, Indie88 and Stingray Music

### PR DESCRIPTION
**Pull request by jbwharris**
**Describe the changes you made**
Added new connector for three Canadian services, CBC Music, Indie88 and Stingray Music

**CBC Music**
Only works for Music Playlists and not their streaming radio, since their web streams don't have meta data.

**Indie88**
Works with the popup player (https://cob.leanplayer.com/CINDFM) and the full page player (https://indie88.com/lean-stream-player/)

**Stingray Music**
This one works well if you're using an ad blocker like uBlock Origin, but I had noted issues with being a track behind when it did ad insertion that I wasn't able to figure out.

### CODE REVIEW

**Comment by alexesprit** [comment]
Could you submit each connector in a separate PR?

**Comment by jbwharris** [comment]
@alexesprit I will be able to submit them separately tonight. How do I best handle connectors.js additions for each PR?

**Comment by inverse** [comment]
@jbwharris Git should be able to handle that 👍🏼 There might be minor conflicts but shouldn't be so bad.

**Comment by alexesprit** [comment]
@jbwharris you can use separate branches per each connector. I'll resolve merge conflicts by myself. :)

**Pull request closed without merging**
