### PR TITLE
Implement Flo Connector

### PR DESCRIPTION
**Pull request by SuyeonChoi**
Hello I want to use this extension in Flo(https://www.music-flo.com/)
Could you check my request please?

### CODE REVIEW

**Comment by alexesprit** [comment]
Could you rename the connector file and the connector ID to match the 2nd level domain (`music-flo`)?

**Comment by inverse** [comment]
@SuyeonChoi any update on this one?

**Comment by SuyeonChoi** [comment]
It was my first time working on an open source project so it seems like I've made some mistakes. The changes works for me but I don't understand why some checks are not successful.

**Comment by inverse** [comment]
@SuyeonChoi Looking good! Thanks for taking the time to contribute. 

You're missing a new line at the end of the file.

**Comment by alexesprit** [comment]
@SuyeonChoi Thanks for contributing!

This project has strict requirements for code formatting, and contributing to this one could be a challenge for newcomers.

**Pull request merged**
