### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by osvaldobarrera**
Changed "Álbum del artista" (tr: artist album) to "Artista del álbum" (tr: album artist).

### CODE REVIEW

**Comment by salazarbarrera** [comment]
I made a transifex account and sent the suggestion there. Effectively, I can only suggest, not edit. Thanks for your help!

**Comment by inverse** [comment]
Not an expert with Transifex, I don't remember having to approve other folks translations.

**Comment by yayuyokitano** [comment]
> Not an expert with Transifex, I don't remember having to approve other folks translations.
> 
> Def need a way to automate things in this area more.

Its because it’s an edit of an already reviewed translation, rather than a new translation

**Comment by yayuyokitano** [comment]
Late, but this has now been corrected in transifex. Once new transifex merge is done it will come in the version after that. Closing.

**Pull request closed without merging**
