### PR TITLE
Added support for Atomic Music Space

### PR DESCRIPTION
**Pull request by clasick**
**Describe the changes you made**
Added support for Atomic Music Space as requested by @Vyktory in https://github.com/web-scrobbler/web-scrobbler/issues/2152

### CODE REVIEW

**Comment by clasick** [comment]
Not sure why there are 8 commits in this PR (only the last two are related to this), but the diffs only show the proper changes. Hope this is fine.

**Comment by alexesprit** [comment]
> Not sure why there are 8 commits in this PR (only the last two are related to this), but the diffs only show the proper changes. Hope this is fine.

You can use separate branches for PRs to avoid this.

**Comment by clasick** [comment]
> > Not sure why there are 8 commits in this PR (only the last two are related to this), but the diffs only show the proper changes. Hope this is fine.
> 
> You can use separate branches for PRs to avoid this.

Cool. I'll remember this for next time.

**Comment by alexesprit** [comment]
The connector works fine for me. 

Could you also improve it by adding support for current time and duration?

**Comment by clasick** [comment]
> The connector works fine for me.
> 
> Could you also improve it by adding support for current time and duration?

Sure, I'll look into it.

**Comment by clasick** [comment]
> The connector works fine for me.
> 
> Could you also improve it by adding support for current time and duration?

How do I test if the added current time and duration are working? Any easy way, or any changes from  the default behavior that would be noticeable?

**Comment by alexesprit** [comment]
> How do I test if the added current time and duration are working? Any easy way, or any changes from the default behavior that would be noticeable?

There are two options:
1. Use Chrome DevTools Console (Ctrl+Shift+I, "Console" tab). The extension prints track info on every track change in readable format. Note that `currentTime` property can be null, that's ok.
2. Use debug view in the info popup window. You can Alt-click on the popup body, and the debug view will be displayed.

Note that these ways are not available if you running the extension from `build` directory, but not from `src` directory directly. To be honest, I don't know if it's an issue or not; personally I use the extension from the source directory and don't build it, and I really don't know how other people develop and debug the extension. :(

image

**Comment by alexesprit** [comment]
> I realize it must be something to do with "scrobble after 50% of the song is done" or something like that. I can find remainingTime being used by getCurrentState() in connect.js, but I can't find the region of code that uses that.

Yes, duration is used by the core to calculate scrobbling point correctly (50% of the duration or 240 seconds). Current time is not used directly, but it's should be implemented if available to use it in future.

Remaining time is not used by the core directly, but is used by base connector to calculate current time or duration. Some websites contain remaining time instead of current time or duration, and `Connector.getRemainingTime` or `Connector.remainingTimeSelector` can be used for such cases. In the context of Atomic Music Space, remaining getter/selector should not be used.

**Comment by clasick** [comment]
Thanks for the info. I was able to confirm that the previous commit works correctly. 

One thing of note is that running the extension from `src` directly doesn't work on Firefox, had to switch to Chromium to test that part. Not sure if it's just my setup or not either.

**Comment by alexesprit** [comment]
> One thing of note is that running the extension from src directly doesn't work on Firefox, had to switch to Chromium to test that part. Not sure if it's just my setup or not either.

You're totally right, that's an issue for Firefox users/devs. I'll fix that. Thanks for opening my eyes to this problem.

The connector is perfect now. Merging right away.

**Pull request merged**
