### PR TITLE
Fix Indie88 Connector

### PR DESCRIPTION
**Pull request by jbwharris**
**Describe the changes you made**
Indie88 changed their layout a bit recently and I've adjusted the connector accordingly. 

**Additional context**
image

### CODE REVIEW

**Comment by inverse** [comment]
Hi @jbwharris thanks for the PR but I'm struggling to see whats changed aside whitespace.

See: https://github.com/web-scrobbler/web-scrobbler/pull/3050/files

**Comment by jbwharris** [comment]
@inverse Sorry about that, when starting over I copied the wrong indie88.js from the folder. This is definitely the one that I've been using successfully in Edge.

**Comment by inverse** [comment]
No need to say sorry 👍🏼 Thanks for taking the time to make sure it's correct.

**Comment by jbwharris** [comment]
@inverse I appreciate the patience with this. This has been my way to learn Git a little better, but obviously I'm still struggling with it. I actually have a bunch of other connectors I've written that I have to submit so I'll get this process down yet.

**Pull request merged**
