### PR TITLE
Activate filters for the Tidal music service

### PR DESCRIPTION
**Pull request by rgoudie**
Code was added to allow the extension to filter track and album text
litter for the Tidal music service.

More filters were added to catch more "remaster"-like track litter
as well as "(single version)"-like track litter.

### CODE REVIEW

**Comment by alexesprit** [comment]
@rgoudie Hi, nice changes! Could you also update tests of remastered filters, and add tests of tidal filter?

**Comment by rgoudie** [comment]
Hello.
Sure, I can do that. I'll give it a look after I complete my work day. Thanks.
-Ray.

    On Sunday, August 18, 2019, 11:51:27 p.m. PDT, Alexey <notifications@github.com> wrote:  @rgoudie Hi, nice changes! Could you also update tests of remastered filters, and add tests of tidal filter?

**Comment by rgoudie** [comment]
Sorry for the delay. I have been working long days. I will probably only have time and energy on Saturday to finalize.Thanks.

    On Sunday, August 18, 2019, 11:51:27 p.m. PDT, Alexey <notifications@github.com> wrote:  @rgoudie Hi, nice changes! Could you also update tests of remastered filters, and add tests of tidal filter?

**Comment by jaccarmac** [comment]
I've got a PR languishing which deals with some of these cases in a different way. Thanks for the additional cases, I'm looking forward to cleaner scrobbles with Tidal!

**Comment by rgoudie** [comment]
@jaccarmac, You're welcome!

My ultimate goal is to never again see track- and album-title litter in my scrobbles.

**Comment by rgoudie** [comment]
This is my first time working with GIT. Was my commit from yesterday successful???

**Comment by jaccarmac** [comment]
I can see 'em!

**Comment by inverse** [comment]
@rgoudie the build is failing see: https://travis-ci.org/web-scrobbler/web-scrobbler/builds/576335653

```
/home/travis/build/web-scrobbler/web-scrobbler/tests/content/filter.js
  602:1  error  Expected indentation of 0 tabs but found 1  indent
```

**Comment by alexesprit** [comment]
You can view errors by clicking on "Details" button:
image

**Comment by rgoudie** [comment]
Is there anything else that I need to do?

**Comment by alexesprit** [comment]
@rgoudie yes, two tests are broken. You can click on "Details" link to view errors.

**Comment by rgoudie** [comment]
Okay, so it must be that I did not push my corrections properly. I did fix the errors from 4 days ago.

**Pull request merged**
