### PR TITLE
RadioParadise.js modify to new Wep player

### PR DESCRIPTION
**Pull request by JeonHyungJin**
I modifired RadioParadise.js file to new web player!
about this [PR](https://github.com/web-scrobbler/web-scrobbler/pull/1729)
And at that PR i modified connectors.js file for running this program in "earbits.com" site when user use without "www".
Is that ok to commit again about that part?

### CODE REVIEW

**Comment by inverse** [comment]
What id the new web player? From what I can see that site has:

- header player
- slideshow player
- Audio player
- Beta player

I think changing just for the new one isn't the right way to go. Supporting multiple player elements would be the best way to do this. 

To do this you should check for the existence of an element and setup the behaviour if that's found for that player.

**Comment by JeonHyungJin** [comment]
Web site which you are talking about is RadioParadise.com?!

**Comment by inverse** [comment]
radio paradise eclectic commercial free internet radio


See the screenshot

**Comment by JeonHyungJin** [comment]
okay i see. I will do again😊

**Comment by inverse** [comment]
Have a look at how we do it for the Deezer connector.

https://github.com/web-scrobbler/web-scrobbler/blob/f627a7076f2a17d3989f8a3ad231d49065158b73/src/connectors/deezer.js

Basically loading the right logic based on a DOM element existence.

**Comment by inverse** [comment]
Closing as resolved in another PR. Feel free to extend to add support for other sites as required

**Pull request closed without merging**
