### PR TITLE
Handle single quotes in Youtube titles

### PR DESCRIPTION
**Pull request by reitzig**
Test case for #1796

### CODE REVIEW

**Comment by reitzig** [comment]
Hm, the problem seems to lie elsewhere.

**Comment by reitzig** [comment]
Not knowing the use cases for that filter, it's hard to make a guess as to what's necessary. Having `.*` in there begs for trouble, imho.

Would it help to solve those use cases by adding a suitable regexp to `youtubeTitleRegExps` (in a suitable position)? Meaning, if the part between quotes is a suitable artist+title thing, use that; if not, try the next pattern (the existing ones).

**Comment by inverse** [comment]
Exactly - it's really hard to gauge the usage.

Unfortunately the way the filters work right now is that'll run them all through a title before sending off to last.fm - which IMHO makes sense to some degree.

I think having some min-length could work as these right now will assume the track title to be empty if it's just single quotes.

**Comment by inverse** [comment]
Looks like the regex needs whitespace around the `'` so it's not as bad as it seems. Only the ones with `'n'` would fail.

**Comment by inverse** [comment]
Merged the other PR that should fix it. I wonder why this was still passing before with what you added :/ Will need to investigate.

**Comment by inverse** [comment]
So it turns out that that test case you added just covers https://github.com/web-scrobbler/web-scrobbler/blob/master/src/core/content/util.js#L32

**Comment by inverse** [comment]
Closing due to other test case covering this. Eventually we should tidy up this logic as there are some filters going on in util that should be consolidated.

**Pull request closed without merging**
