### PR TITLE
Webscrobbler creates wrong info flag in Vivaldi browser

### PR DESCRIPTION
**Pull request by stardepp**
Yesterday I installed the latest version of Webscrobbler in Vivaldi for Windows 10. The notification flag of webscrobbler is simply grayed out and prevents the original Windows notification. Please fix this bug.

### CODE REVIEW

**Comment by alexesprit** [comment]
What is this?

**Comment by stardepp** [comment]
see here:  https://forum.vivaldi.net/topic/41646/benachrichtigungsfähnchen-von-oben-rechts-nach-unten-rechts-verschieben

**Comment by alexesprit** [comment]
Sorry, I don't understand Deutch.

**Comment by stardepp** [comment]
> Sorry, I don't understand Deutch.

Here in english: file:///C:/Users/stgru/Downloads/move notification flags from top right to bottom right _ vivaldi forum.pdf

**Comment by alexesprit** [comment]
I'm closing this one, as PRs are not intended for reporting issues.

> Here in english: file:///C:/Users/stgru/Downloads/move notification flags from top right to bottom right _ vivaldi forum.pdf

Really?

**Comment by stardepp** [comment]
Sorry, hier in english: https://drive.google.com/file/d/1bbn-eptcXT-85OryvzMW_7C-gXpvZwnH/view?usp=sharing

**Comment by alexesprit** [comment]
@stardepp I'm quite curious, so I translated messages using Google Translate.

I don't know what is a flag you're talking about, but the extensions (not this one only, but **all** Chrome-based extensions) **cannot** set up notification position.

**Pull request closed without merging**
