### PR TITLE
fix OnlineRadioBox connector

### PR DESCRIPTION
**Pull request by anthortic**
**Describe the changes you made**

fix onlineradiobox connector.

**Additional context**

further info in issue #4787

### CODE REVIEW

**Comment by anthortic** [comment]
no idea how to add the 'fixed-connector' label.
sorry

**Comment by inverse** [comment]
Hi @anthortic thanks for the contribution! where is the issue with the current connector? 

When I visit onlineradiobox.com it seems to work fine for me but the URL change in this pull request I can't seem to find?

**Comment by anthortic** [comment]
Hi @inverse thanks for checking it out. 

When I click the play button, the player now pops out a new window to the sub domain p.onlineradiobox.com which the extension does not pick up as it is now.

**Comment by anthortic** [comment]
I suppose I should have put:

matches: ['*://onlineradiobox.com/*', '*://p.onlineradiobox.com/*'],

Do you think?

**Comment by inverse** [comment]
@anthortic that makes sense if it's available on multiple URLs! go for it!

**Review by inverse — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
