### PR TITLE
Add connector for Telegram Web

### PR DESCRIPTION
**Pull request by Mehavoid**
Resolve: #4238 #3697

### CODE REVIEW

**Comment by dabajabaza** [comment]
@Mehavoid I'm using your telegram connector for almost a week now. Everything is ok. Thank you!

**Comment by yayuyokitano** [comment]
This is still marked as draft after months of inactivity. Is this intended to no longer be draft?

**Comment by yayuyokitano** [comment]
Cool. Btw linter errors here can be fixed by running `npm run prettierfix`

**Review by yayuyokitano — APPROVED** [review]
Sorry, missed that this had been marked as ready for review. LGTM! Thank you for the contribution!

**Comment by IRainman** [comment]
Yay, thank you!

**Comment by IRainman** [comment]
> [Mehavoid](https://github.com/Mehavoid) писал(а) 2024-01-31 21:21:
> Enjoy! Feel free to report any issues.

Current release don't have the Telegram support :')

**Pull request merged**
