### PR TITLE
Update ibroadcast.js

### PR DESCRIPTION
**Pull request by flagoworld**
Updated iBroadcast connector for new website UI

### CODE REVIEW

**Comment by ctrueden** [comment]
@flagoworld Ahh, you beat me to it! Thanks! LGTM to me. :+1:

**Comment by ctrueden** [comment]
@alexesprit Could this be merged and released soon? I'm really looking forward to scrobbling from the iBroadcast website again!

**Comment by inverse** [comment]
Thanks 👍🏼

**Comment by inverse** [comment]
@ctrueden we should be releasing a new version by a few days - just need to go through some other PRs to get those checked too 👍🏼

**Comment by inverse** [comment]
@ctrueden sorry for the delay - It's been published https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.45.1

**Pull request merged**
