### PR TITLE
Update connectors - nugs.net and livephish

### PR DESCRIPTION
**Pull request by MikeLP**
# Changelog

- Updated nugs.net player selectors to improve integration with Web Scrobbler.
- Updated livephish player selectors to improve integration with Web Scrobbler.

**Additional context**

This PR addresses the latest markup changes on [nugs.net web player](https://play.nugs.net/) and [livephish web player](https://plus.livephish.com/) we made for `Web Scrobbler` extension.

### CODE REVIEW

**Comment by MikeLP** [comment]
Currently nugs.net web player and LP web player share the UI.

**Review by inverse — CHANGES_REQUESTED** [review]
Looks like there are linter warnings.

You should be able to run `npm run prettierfix` to fix it

**Comment by inverse** [comment]
@MikeLP do you want me to help with fixing the linter issues on your branch?

**Comment by MikeLP** [comment]
> @MikeLP do you want me to help with fixing the linter issues on your branch?

Sure. Thanks!

**Review by inverse — APPROVED** [review]

**Pull request merged**
