### PR TITLE
implement mnet Connector

### PR DESCRIPTION
**Pull request by JungTaepyo**
mnet is a korean music streaming page.

### CODE REVIEW

**Comment by inverse** [comment]
Could you fix the CI issues :+1:

**Comment by inverse** [comment]
@JungTaepyo  can you fix the CI and merge issues? or shall I take over?

**Comment by jaccarmac** [comment]
Is this PR necessary any more or does the existing connector work?

**Comment by inverse** [comment]
Looks redundant now.

**Pull request closed without merging**
