### PR TITLE
Add connector for tunes.apt-get.xyz

### PR DESCRIPTION
**Pull request by lc-guy**
**Describe the changes you made**
Support for my [radio DJ archive](https://tunes.apt-get.xyz/). MediaSession support handles it all fine.

**Additional context**
None in particular.

### CODE REVIEW

**Comment by yayuyokitano** [comment]
Please run `npm run prettierfix` to fix prettier issues.

**Comment by lc-guy** [comment]
> Please run `npm run prettierfix` to fix prettier issues.

done.

**Comment by yayuyokitano** [comment]
Thank you!
A merge conflict was introduced, probably due to the merging of another connector

**Comment by lc-guy** [comment]
> Thank you! A merge conflict was introduced, probably due to the merging of another connector

Fixed as well.

**Comment by yayuyokitano** [comment]
Thank you! LGTM!

**Pull request merged**
