### PR TITLE
New Mirlo connector

### PR DESCRIPTION
**Pull request by jbwharris**
New connector for https://mirlo.space

I do have concerns about whether the selectors for this one will stay consistent, but I guess we'll see. 

image

### CODE REVIEW

**Comment by jbwharris** [comment]
@simonv3 Most definitely. I just had concern that potentially the classes I targeted could change in a future build.

**Review by inverse — APPROVED** [review]
Yeah those names feel like it's gonna be hard to keep up with :/ While I get why to keep things lean doing the build, it makes it harder for extensions to add functionality on top.

**Comment by simonv3** [comment]
Going to add ids:

`#player`, `#player-track-title`, `#player-trackGroup-title`, `#player-artist-name`

You'll be able to get the image with `#player img` and the play button with `#player .play-button`.

Will be merged in https://github.com/funmusicplace/mirlo/pull/790

**Comment by jbwharris** [comment]
> Going to add ids:
> 
> 
> 
> `#player`, `#player-track-title`, `#player-trackGroup-title`, `#player-artist-name`
> 
> 
> 
> You'll be able to get the image with `#player img` and the play button with `#player .play-button`.
> 
> 
> 
> Will be merged in https://github.com/funmusicplace/mirlo/pull/790

I am currently on vacation and probably won't get to this for a few days. Thanks for making those changes!

**Comment by inverse** [comment]
@simonv3 that's awesome! 

@jbwharris lets hold off to get it working properly.

**Comment by jbwharris** [comment]
@inverse @simonv3 Just pushed over the changes

**Comment by inverse** [comment]
@jbwharris I think the last commit needs to be reverted as it changes other connectors

**Comment by jbwharris** [comment]
@inverse I just reverted my last commit. I had thought I needed to update it to the latest connectors.ts since it had been a bit since my initial pr.

**Review by inverse — APPROVED** [review]

**Pull request merged**
