### PR TITLE
Add pan y rosas discos connector.

### PR DESCRIPTION
**Pull request by jaccarmac**
pan y rosas discos is a Chicago netlabel which puts out various kinds of experimental music. This connector seems to work well on most of the catalog, though it looks like pyr060 and older use a different player. Support for that player is not implemented yet.

### CODE REVIEW

**Comment by jaccarmac** [comment]
Does inlining it like that work or is it better to have the splitting separate so the `uniqueID` is set elsewhere?

**Comment by jaccarmac** [comment]
Album art seems to be in slightly different places in the DOM every time. Can just remove that selector entirely if `:eq(0)` is too much of a hack.

**Comment by alexesprit** [comment]
> Does inlining it like that work or is it better to have the splitting separate so the uniqueID is set elsewhere?

It's fine for me.

**Comment by jaccarmac** [comment]
In that case we should be set.

**Pull request merged**
