### PR TITLE
run npm audit fix + fix minimalist

### PR DESCRIPTION
**Pull request by inverse**
- Pin `minimist`
- Run `npm audit fix`

### CODE REVIEW

**Comment by alexesprit** [comment]
Adding `minimist` as a dev dependency doesn't resolve the issue:
<details>
  <summary>npm audit output with minimist 1.2.5 installed (Click to expand)</summary>

```
$ npm audit        

                       === npm audit security report ===                        

# Run  npm update tar-fs --depth 4  to resolve 1 vulnerability

  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Dependency of   grunt-contrib-compress [dev]                                  

  Path            grunt-contrib-compress > iltorb > prebuild-install > tar-fs   
                  > mkdirp > minimist                                           

  More info       https://npmjs.com/advisories/1179                             




                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   codacy-coverage [dev]                                         

  Path            codacy-coverage > jacoco-parse > mocha > mkdirp > minimist    

  More info       https://npmjs.com/advisories/1179                             


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   grunt-contrib-compress [dev]                                  

  Path            grunt-contrib-compress > iltorb > prebuild-install > mkdirp   
                  > minimist                                                    

  More info       https://npmjs.com/advisories/1179                             


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-svgo > svgo > mkdirp >      
                  minimist                                                      

  More info       https://npmjs.com/advisories/1179                             


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   grunt-eslint [dev]                                            

  Path            grunt-eslint > eslint > file-entry-cache > flat-cache >       
                  write > mkdirp > minimist                                     

  More info       https://npmjs.com/advisories/1179                             


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   stylelint [dev]                                               

  Path            stylelint > file-entry-cache > flat-cache > write > mkdirp >  
                  minimist                                                      

  More info       https://npmjs.com/advisories/1179                             


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   grunt-eslint [dev]                                            

  Path            grunt-eslint > eslint > mkdirp > minimist                     

  More info       https://npmjs.com/advisories/1179                             


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   grunt-lintspaces [dev]                                        

  Path            grunt-lintspaces > junitwriter > mkdirp > minimist            

  More info       https://npmjs.com/advisories/1179                             


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   stylelint [dev]                                               

  Path            stylelint > postcss-sass > gonzales-pe > minimist             

  More info       https://npmjs.com/advisories/1179                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-gifsicle > gifsicle >       
                  bin-build > decompress                                        

  More info       https://npmjs.com/advisories/1217                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-jpegtran > jpegtran-bin >   
                  bin-build > decompress                                        

  More info       https://npmjs.com/advisories/1217                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-optipng > optipng-bin >     
                  bin-build > decompress                                        

  More info       https://npmjs.com/advisories/1217                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-gifsicle > gifsicle >       
                  bin-build > download > decompress                             

  More info       https://npmjs.com/advisories/1217                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-jpegtran > jpegtran-bin >   
                  bin-build > download > decompress                             

  More info       https://npmjs.com/advisories/1217                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-optipng > optipng-bin >     
                  bin-build > download > decompress                             

  More info       https://npmjs.com/advisories/1217                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-gifsicle > gifsicle >       
                  bin-wrapper > download > decompress                           

  More info       https://npmjs.com/advisories/1217                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-jpegtran > jpegtran-bin >   
                  bin-wrapper > download > decompress                           

  More info       https://npmjs.com/advisories/1217                             


  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   grunt-contrib-imagemin [dev]                                  

  Path            grunt-contrib-imagemin > imagemin-optipng > optipng-bin >     
                  bin-wrapper > download > decompress                           

  More info       https://npmjs.com/advisories/1217                             

found 18 vulnerabilities (9 low, 9 high) in 7575 scanned packages
  run `npm audit fix` to fix 1 of them.
  17 vulnerabilities require manual review. See the full report for details.
```
</details>

**Comment by inverse** [comment]
Interesting - how did it cause the security alerts on GH to be alright than? It's even what they were advising to do.

**Comment by alexesprit** [comment]
@inverse I don't really know.

We don't use `minimist` directly, and other packages we use as dependencies have outdated `minimist` that we cannot change (and this is quite obvious). That's why this is still an issue, even after pinning `minimist` in our `package.json`.

**Comment by inverse** [comment]
Wonder why they advised it then :/ npm dependency graphs sound crazy

**Pull request merged**
