### PR TITLE
Add duration parsing to Amazon Alexa connector

### PR DESCRIPTION
**Pull request by benscobie**
The Amazon Alexa SPA app has a Now Playing tab which includes additional metadata about the currently playing song. We can use this to parse the duration time of the song. The user will need to navigate and stay on the Now Playing tab in order for this new functionality to work. This appears to fallback gracefully if the user is not on the Now Playing tab though.

I've had to include a workaround to get around the fact that the UI does not update some of the metadata straight away when changing song which lead to incorrect duration time calculations.

**Note**: This **was** working on the v2.3.x branch but does not appear to work in master, even without my changes. It doesn't detect that a song is playing.

### CODE REVIEW

**Comment by alexesprit** [comment]
> Note: This was working on the v2.3.x branch but does not appear to work in master, even without my changes. It doesn't detect that a song is playing.

Is this true for Amazon Alexa only?

**Comment by benscobie** [comment]
I've tried the YouTube connector and that seems to work okay.

**Comment by alexesprit** [comment]
@benscobie Could you try to use `length` property instead of `size` function when checking element count?

**Comment by benscobie** [comment]
Done. Do you want me to take a look as to why the connector isn't working in master?

**Comment by alexesprit** [comment]
@benscobie I supposed it didn't work because of `size` function (I updated jQuery recently). Yes that would be great, if you could figure out why the connector doesn't work on master.

Probably, it's something wrong in content scripts.

[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-content-scripts

**Comment by benscobie** [comment]
I can confirm it's working in master after the size() replacement.

**Comment by alexesprit** [comment]
Nice, thanks!

**Pull request merged**
