### PR TITLE
Add .gitattributes to prevent conversion to CRLF

### PR DESCRIPTION
**Pull request by RudeySH**
I've added a .gitattributes file with `* eol=lf` to force Git to normalize line endings to LF on checkin and prevent conversion to CRLF when files are checked out.

**Additional context**

The default config of Git for Windows is in conflict with web-scrobbler's lint.

- Git's "core.autocrlf" setting allows developers on Windows to automatically convert line endings to CRLF when checking out files, and normalizes line endings back to LF on checkin. While core.autocrlf is set to false by default, **the Git for Windows installer sets core.autocrlf to true by default**. Effectively, most developers on Windows will get CRLF line endings when checking out files.

- CRLF line endings lead to warnings in web-scrobbler's lint (specifically, [lintspaces](https://github.com/schorfES/node-lintspaces)), and converts CRLF back to LF.

As a result of of using both core.autocrlf=true and lintspaces, checking out web-scrobbler on Windows and then running lint will instantly result in hundreds of thousands of warnings, and hundreds of modified files.

<details>
<summary>View output</summary>

```
$ npm run lint

> web-scrobbler@2.57.2 lint
> grunt lint

Running "eslint:target" (eslint) task

Running "jsonlint:src" (jsonlint) task
>> 11 files lint free.

Running "lintspaces:src" (lintspaces) task
☓ package-lock.json
  L1: Incorrect end of line character(s) found.
  L2: Incorrect end of line character(s) found.
  L3: Incorrect end of line character(s) found.
  L4: Incorrect end of line character(s) found.
  L5: Incorrect end of line character(s) found.
  L6: Incorrect end of line character(s) found.
  L7: Incorrect end of line character(s) found.
  L8: Incorrect end of line character(s) found.
  L9: Incorrect end of line character(s) found.
  L10: Incorrect end of line character(s) found.
  L11: Incorrect end of line character(s) found.
  L12: Incorrect end of line character(s) found.
  L13: Incorrect end of line character(s) found.
  L14: Incorrect end of line character(s) found.
  L15: Incorrect end of line character(s) found.
  L16: Incorrect end of line character(s) found.
  L17: Incorrect end of line character(s) found.
  L18: Incorrect end of line character(s) found.
  L19: Incorrect end of line character(s) found.
  L20: Incorrect end of line character(s) found.
  L21: Incorrect end of line character(s) found.
  L22: Incorrect end of line character(s) found.
  L23: Incorrect end of line character(s) found.
  L24: Incorrect end of line character(s) found.
  L25: Incorrect end of line character(s) found.
  L26: Incorrect end of line character(s) found.
  L27: Incorrect end of line character(s) found.
  L28: Incorrect end of line character(s) found.
  L29: Incorrect end of line character(s) found.
  L30: Incorrect end of line character(s) found.
  L31: Incorrect end of line character(s) found.
  L32: Incorrect end of line character(s) found.
  L33: Incorrect end of line character(s) found.
  L34: Incorrect end of line character(s) found.
  L35: Incorrect end of line character(s) found.
  L36: Incorrect end of line character(s) found.
  L37: Incorrect end of line character(s) found.
  L38: Incorrect end of line character(s) found.
  L39: Incorrect end of line character(s) found.
  L40: Incorrect end of line character(s) found.
  L41: Incorrect end of line character(s) found.
  L42: Incorrect end of line character(s) found.
  L43: Incorrect end of line character(s) found.
  L44: Incorrect end of line character(s) found.
  L45: Incorrect end of line character(s) found.
  L46: Incorrect end of line character(s) found.
  L47: Incorrect end of line character(s) found.
  L48: Incorrect end of line character(s) found.
  L49: Incorrect end of line character(s) found.
  L50: Incorrect end of line character(s) found.
  L51: Incorrect end of line character(s) found.
  L52: Incorrect end of line character(s) found.
  L53: Incorrect end of line character(s) found.
  L54: Incorrect end of line character(s) found.
  L55: Incorrect end of line character(s) found.
  L56: Incorrect end of line character(s) found.
  L57: Incorrect end of line character(s) found.
  L58: Incorrect end of line character(s) found.
  L59: Incorrect end of line character(s) found.
  L60: Incorrect end of line character(s) found.
  L61: Incorrect end of line character(s) found.
  L62: Incorrect end of line character(s) found.
  L63: Incorrect end of line character(s) found.
  L64: Incorrect end of line character(s) found.
  L65: Incorrect end of line character(s) found.
  L66: Incorrect end of line character(s) found.
  L67: Incorrect end of line character(s) found.
  L68: Incorrect end of line character(s) found.
  L69: Incorrect end of line character(s) found.
  L70: Incorrect end of line character(s) found.
  L71: Incorrect end of line character(s) found.
  L72: Incorrect end of line character(s) found.
  L73: Incorrect end of line character(s) found.
  L74: Incorrect end of line character(s) found.
  L75: Incorrect end of line character(s) found.
  L76: Incorrect end of line character(s) found.
  L77: Incorrect end of line character(s) found.
  L78: Incorrect end of line character(s) found.
  L79: Incorrect end of line character(s) found.
  L80: Incorrect end of line character(s) found.
  L81: Incorrect end of line character(s) found.
  L82: Incorrect end of line character(s) found.
  L83: Incorrect end of line character(s) found.
  L84: Incorrect end of line character(s) found.
  L85: Incorrect end of line character(s) found.
  L86: Incorrect end of line character(s) found.
  L87: Incorrect end of line character(s) found.
  L88: Incorrect end of line character(s) found.
  L89: Incorrect end of line character(s) found.
  L90: Incorrect end of line character(s) found.
  L91: Incorrect end of line character(s) found.
  L92: Incorrect end of line character(s) found.
  L93: Incorrect end of line character(s) found.
  L94: Incorrect end of line character(s) found.
  L95: Incorrect end of line character(s) found.
  L96: Incorrect end of line character(s) found.
  L97: Incorrect end of line character(s) found.
  L98: Incorrect end of line character(s) found.
  L99: Incorrect end of line character(s) found.
  L100: Incorrect end of line character(s) found.

...

Warning: Formatting check failed. Use --force to continue.

Aborted due to warnings.
```
</details>

I can think of two possible solutions:

1. Remove, disable or configure lintspaces so that it no longer cares about line endings.
2. Prevent Git from converting line endings when checking out this repository, which is what this PR aims to achieve.

### CODE REVIEW

**Comment by RudeySH** [comment]
Note that `* eol=lf` will normalize line endings for **all** files, not just the files that the lintspaces checks. We could also opt to use something like this:

```
*.js eol=lf
*.json eol=lf
```

Personally, I think that because Git already allowed for fine-grained control over line endings, having lintspaces check for line endings is redundant, if not intrusive. With a .gitattributes file in place, all that lintspaces does is annoy developers who want to use CRLF in their working directory. I think lintspaces should be removed. But I'll leave that up to the maintainers.

**Comment by inverse** [comment]
We're already using [EditorConfig](https://editorconfig.org/) to achieve this.

See https://github.com/web-scrobbler/web-scrobbler/blob/master/.editorconfig#L5

**Comment by RudeySH** [comment]
The .editorconfig file tells text editor programs to convert line ending to LF when saving a file. The .editorconfig file does not prevent Git from converting the line endings when files are checked out.

Allow me to explain in further detail what happens right now when checking out this repo on Windows using a **default Git installation**:

1. Clone the repo, all the line endings in files are now converted to CRLF. This is what happens by default in Git on Windows, regardless of what line endings the files have in GitHub. Regardless of the .editorconfig.
2. Open a file, and save it without changing anything. Now the line endings of that file are converted to LF because of .editorconfig. You now have a dirty working directory in Git, because the line endings are different from what Git is configured to use.
3. Run `npm run lint`, you get hundreds of thousands of warnings, and your working directory now contains 300+ dirty files.

I hope we can agree this is something that should be fixed.

**Comment by inverse** [comment]
🙏🏼 thanks for taking the time to explain.

**Comment by RudeySH** [comment]
Thanks for merging this! Now everything works as expected on Windows.

<details>
<summary>View output</summary>

```
npm run lint

> web-scrobbler@2.57.2 lint
> grunt lint

Running "eslint:target" (eslint) task

Running "jsonlint:src" (jsonlint) task
>> 11 files lint free.

Running "lintspaces:src" (lintspaces) task
>> 354 lint free.

Running "stylelint:all" (stylelint) task
>> Linted 5 files without errors

Running "remark:src" (remark) task

Running "unused_files" task
>> No unused files are found

Done.
```

</details>

**Comment by inverse** [comment]
Thanks for going the extra mile explaining too!

**Comment by eugenesvk** [comment]
This PR breaks my Windows git that already has `[core] autocrlf=false` on all 35 of `*.png` files in `src\icons` in a much worse way than having some lint warnings — I can't switch branches because git thinks these files have  been edited (even though they haven't been edited)

Can we go back to the less intrusive first option mentioned in the PR and directly fix the `lintspaces`?
Meanwhile I'll add a PR that implements a more limited solution listed in the second comment that applies the EOL changes to code files only

**Pull request merged**
