### PR TITLE
Fix connector for Deezer 

### PR DESCRIPTION
**Pull request by Mehavoid**
Closes: https://github.com/web-scrobbler/web-scrobbler/issues/3337, https://github.com/web-scrobbler/web-scrobbler/issues/3350

- Fix detect first playing
- Fix correct handle next track
- Fix step backword
- Fix `Flow` mode

### CODE REVIEW

**Review by inverse — APPROVED** [review]
Thanks :+1:

**Comment by hans-juergen** [comment]
Thank you very much for fixing this issue, as it was the missing link to finally have correct scrobbles, lossless HiFi streaming and gapless playback in one app on the desktop computer. 😎

Additional bonus is the available [Discord integration](https://chrome.google.com/webstore/detail/deezer-discord-integratio/gpmnalhimebpjhilkifcaadejhmogaok) for the Deezer web player with an external browser extension, so Last.fm's recent tracks, .fmbot commands and your Discord account all show the same info. Last but not least the fullscreen online tool [Descent](https://descent.live/now) works with Deezer now as well as Last.fm's "Scrobbling now" fullscreen feature for Pro users.

**Comment by mariomarinato** [comment]
I still face the problem described on ticket #3337.

**Comment by hans-juergen** [comment]
Have you made sure that your browser actually has the new version 2.72.0? I have tested it with the Chrome version of the extension in Edge, and it worked as it should.

**Comment by kachan64** [comment]
thanks guys. works like a charm now!

**Comment by kachan64** [comment]
> I still face the problem described on ticket #3337.

Don't forget to update your browser too. not sure if that matters...

**Comment by mariomarinato** [comment]
> > I still face the problem described on ticket #3337.
> 
> Don't forget to update your browser too. not sure if that matters...

I updated the browser, restarted the computer and, indeed, it's working.  
Shout out to Mehavoid for fixing it.  Thanks!

**Pull request merged**
