### PR TITLE
Implement Bugs connector

### PR DESCRIPTION
**Pull request by JeonHyungJin**
[Bugs Music](https://music.bugs.co.kr) is one of the most famous music player in South Korea.

This pull request adds connector for scrobbling tracks played with Bugs Music web app.

### CODE REVIEW

**Comment by inverse** [comment]
Thnx!

**Comment by JeonHyungJin** [comment]
I am so happy to contribute this project!
the “genie” was the only south korean web site which can use this project.
So i wanted to add other South korean web app. 
Thanks!  :)

**Comment by JeonHyungJin** [comment]
Hello, i have a question about this program.
I thought that i can use this program in "Bugs player" which i merged in this project.
but i can`t use this in that web app.  Is there anything to do more to use this in new web?

**Comment by inverse** [comment]
A new release needs to be published to the market. Unfortunately I don't have the power to do this yet... We need to wait for another core contributor to do this.

**Comment by JeonHyungJin** [comment]
Okay! Thank you for your answer. HAND!

**Comment by hans-juergen** [comment]
Hi, I just tested the Bugs! web site and web player. Scrobbling does not work for me, the greyed out Web Scrobbler icon in the browser says that the site is not supported. The web player is actually popping up as a new browser window, maybe they have changed that recently. But at least it plays 1 min. song excerpts if you click on any play button on the site:

https://music.bugs.co.kr/
https://music.bugs.co.kr/newPlayer

By the way, Melon is the other big online music site in Korea, it also has a web player popping up in a separated browser window, but for me it does not play anything and shows an error about needing the latest Adobe Flash plugin - which I even installed, but not change with it.

**Pull request merged**
