### PR TITLE
Filter track numbers in YouTube chapters

### PR DESCRIPTION
**Pull request by stephanebruckert**
Fixes https://github.com/web-scrobbler/web-scrobbler/issues/2892

### CODE REVIEW

**Comment by stephanebruckert** [comment]
up

**Comment by stephanebruckert** [comment]
@inverse let me know when you can review this, so I can fix conflicts, once :-)

**Comment by stephanebruckert** [comment]
@inverse I removed the package-lock change that was conflicting, any chance for a review? thanks!

**Comment by stephanebruckert** [comment]
Any chance for feedback on this?

**Comment by inverse** [comment]
@stephanebruckert sorry - I must have missed this! thanks for the push :)

**Comment by Offbeatmammal** [comment]
looks like some chapter track numbers are confusing things.
eg https://www.youtube.com/watch?v=YT28Xfl8sEs isn't parsing correctly :(

**Comment by stephanebruckert** [comment]
@Offbeatmammal there is an open issue for it https://github.com/web-scrobbler/web-scrobbler/issues/3070

**Pull request merged**
