### PR TITLE
Add Watch2Gether support 

### PR DESCRIPTION
**Pull request by jamescdcarter**
Fix for Issue #2064

Added an entry in `connectors.js` to enable [Watch2Gether ](https://www.watch2gether.com) support.

**Additional context**

Watch2Gether works by embedding a YouTube iframe.
The `connectors/youtube-embed.js` file works on this website in the same way it does on Discogs.

### CODE REVIEW

**Comment by alexesprit** [comment]
Does it work for you? It does not for me.

**Comment by inverse** [comment]
It's not for me either.

**Comment by jamescdcarter** [comment]
I was woefully naive with this PR.

Not only does watch2gether support other players than just YouTube but it dynmically loads in an iframe (I don't believe this extension supports injecting the content script into dynamic iframes).

I'm looking into monkey patching some of the website's internal events to intercept player state change and track info change.

**Comment by jamescdcarter** [comment]
I've added a new connector that:

 - watches the play button and timer info elements for state change using a `MutationObserver`
 - gets track info from the chat box

**Comment by alexesprit** [comment]
Why did you wrap the code in a class?

**Comment by jamescdcarter** [comment]
After seeing your changes I can see that I over complicated my implementation.

Your refactor looks great!

**Comment by alexesprit** [comment]
Could you push these changes? I'll merge this PR then.

**Comment by jamescdcarter** [comment]
I've pushed the changes and reintroduced the jQuery workaround to decode html entities (there's a bug in watch2gether that results in html entities showing in track names).

**Comment by alexesprit** [comment]
> (there's a bug in watch2gether that results in html entities showing in track names).

Have you an example of such videos? I want to test if the metadata filter that replaces HTML entities will resolve the issue.

**Comment by jamescdcarter** [comment]
Thank you for taking time to explain that to me.

I'd like to pick up a few other requests for connectors so I'll be sure to pay more attention to the docs and lint rules.

it looks as if watch2gether fixed this issue anyway (I've been testing against an old room, removing songs and adding them back in shows the right name now...)

**Comment by alexesprit** [comment]
> it looks as if watch2gether fixed this issue anyway (I've been testing against an old room, removing songs and adding them back in shows the right name now...)

Nice, so the PR is ready to merge, right? It looks good for me, btw.

**Comment by jamescdcarter** [comment]
> Nice, so the PR is ready to merge, right?

Yup, it's all good to go!

**Pull request merged**
