### PR TITLE
Draft new release template

### PR DESCRIPTION
**Pull request by inverse**
**Describe the changes you made**

For the next version I thought it would be nice to have a refined release template to make it clearer. Mostly to seperate new functionality vs new connectors.

Only thing not fully captures is non-connector fixes? Do you think we should handle that?

**Additional context**

I'll need to create the new label's if you agree before merging :+1:

### CODE REVIEW

**Comment by inverse** [comment]
@yayuyokitano what do you think? We could also leverage https://github.com/amannn/action-semantic-pull-request

So that we enforce PR titles follow the conventions to automatically label too

**Comment by yayuyokitano** [comment]
I don't really like semantic pull request linting, as it enforces a pretty strict title format on PRs, rather than label based system where we the maintainers just set up the right labels according to our own discretion. Especially for newer contributors that may be inexperienced I think the current approach is better.

I also think a core fix label is needed, given we have those happen fairly often, i think we have 2-3 updates recently including core fixes.

**Comment by inverse** [comment]
Makes sense for this project indeed.

Added Core fixes - not sure if we need a core updated as updated would cover both updates for core and connectors?

**Comment by inverse** [comment]
will make the label changes

**Pull request merged**
