### PR TITLE
Add support for GRRIF

### PR DESCRIPTION
**Pull request by fetzu**
Adds support for GRRIF.ch

**Describe the changes you made**
Added support for GRRIF.ch's webplayer.

### CODE REVIEW

**Comment by fetzu** [comment]
I'm sorry I've made a bit of a mess in regard to the commits. But it now works a little better and should pass both checks.

Cheers.

**Comment by alexesprit** [comment]
> I'm sorry I've made a bit of a mess in regard to the commits. But it now works a little better and should pass both checks.

No worries, I'll squash your commits. :)

**Comment by alexesprit** [comment]
I'd add support for a track art:
```js
Connector.trackArtSelector = '.pg-history .onair img';

Connector.isTrackArtDefault = (url) => url.includes('default');

**Comment by fetzu** [comment]
> 
> I'd add support for a track art:
> 

Thanks for the feedback (and the code ;)).
Added, tested and pushed.

**Pull request merged**
