### PR TITLE
Fix Epidemic Sound connector

### PR DESCRIPTION
**Pull request by swimtrunks**
updated selectors for new page design 
everything should be in order but open to any feedback.

### CODE REVIEW

**Comment by inverse** [comment]
Resolves #3284

**Review by inverse — APPROVED** [review]
Changes seem legit but I am unable to test - those selectors look like they could be quite brittle due to the IDs look automatically generated.

**Comment by swimtrunks** [comment]
cool. i can dig a bit more. later this week.

**Comment by Umarrii** [comment]
Unable to verify the changes myself either, but a friend who first reported when it stopped working informed me that the it's still not working unfortunately.

**Comment by Arilozen** [comment]
Oh cool! Thanks guys! 👍

**Pull request merged**
