### PR TITLE
Support new SomaFM player

### PR DESCRIPTION
**Pull request by sardaukar**
Change made:

- changed CSS selectors for track and artist name

Still to do:

- detecting whether player is playing or not 

Right now, the only different seems to be that the SVG on the play button changes, from

image

to

image

Fixes https://github.com/web-scrobbler/web-scrobbler/issues/4978

### CODE REVIEW

**Comment by sardaukar** [comment]
OK, realized after posting description on the PR that the track info is only shown next to the player button when actually playing 🤦

**Review by inverse — APPROVED** [review]

**Comment by inverse** [comment]
Thanks!

**Comment by sardaukar** [comment]
Yeah, noticed it too, seems like they updated the new player since then. I'll try to fix it soon.

**Comment by sardaukar** [comment]
Submitted [a new PR](https://github.com/web-scrobbler/web-scrobbler/pull/5049), let's hope it's merged soon. You can use my fork locally until then, if you'd like.

**Pull request merged**
