### PR TITLE
Fix scrobbling on Spotify by updating css selector for artist

### LINKED ISSUE #3019: the bot is not working
I already uninstalled and installed the bot several times in my firefox and nothing came of it, what's happening?

### PR DESCRIPTION
**Pull request by CennoxX**
Spotify changed its website, which causes the web scrobbler to stop working on Spotify, this fixes #3019, #3020 and #3021.
I changed the CSS selector for artists and tested the build locally, where it seemed to be sufficient to get web scrobbler working again on spotify.

### CODE REVIEW

**Comment by dbizamae** [comment]
we will need to wait until the extension modification is approved and implemented.

**Comment by inverse** [comment]
@CennoxX weird `2.46.0` was published automatically on CI with https://github.com/web-scrobbler/web-scrobbler/commit/c25e280f0b99585a21e2f227b71eb1cab138e3f7

**Comment by hans-juergen** [comment]
The change in the Spotify web player seems to be the icon for banning a track or artist from the playbar which was already available in the desktop app as a minus sign. The former web player version had an icon for showing a small player GUI instead which is now gone.

**Comment by fillycolt** [comment]
Solution, at least anecdotally.

https://github.com/web-scrobbler/web-scrobbler/actions/runs/1345112889

Download the web scrobbler file from this page, then replace the files in the already existing extensions folder (within your hidden AppData folder) with the files from the aforementioned link. Restart your browser and try to scrobble a song. It will say the extension is corrupted. Allow the extension to be repaired and restart again, then your scrobbling should be back in order. 

Hope this works for you!

**Pull request merged**
