### PR TITLE
Passthrough URL

### PR DESCRIPTION
**Pull request by inverse**
- Passthrough Origin URL for listenbrainz

### CODE REVIEW

**Comment by Freso** [comment]
Ping: @paramsingh - see discussion starting at https://github.com/web-scrobbler/web-scrobbler/pull/1679#issuecomment-437685104

Currently the PR suggests using `origin_url`, but after my last comment on the other PR, I think the `{track,artist,release}_url` scheme might be a more suitable one. @paramsingh is the lead dev of ListenBrainz though, so maybe he has another view. :)

**Comment by paramsingh** [comment]
Ideally, we'd prefer to know `track_url`, `artist_url` and `release_url` specifically. But if that requires a lot of work, it is probably  okay to submit as much data with the `origin_url` key and then eventually we'll look into matching the data via the [messybrainz](https://messybrainz.org) project.

**Comment by paramsingh** [comment]
So I'd personally merge this for now, and maybe add an issue to submit more granular URLs, so that users can submit as much data to ListenBrainz as possible.

**Comment by inverse** [comment]
@paramsingh thanks for the feedback and insights into the other projects you're working on. Definately something that can be improved to allow "connectors" to provide additional meta data. :+1:

**Comment by MonkeyDo** [comment]
Sorry it took this long to be used on the ListenBrainz side, but we just implemented Youtube as a source for the ListenBrainz player, and it now detects and extracts the Youtube url from listens. Thanks!

For reference: https://github.com/metabrainz/listenbrainz-server/pull/882

**Comment by alexesprit** [comment]
@MonkeyDo Hi! Thanks for the info.

By the way, it wasn't sent to ListenBrainz actually (was fixed recently in 393b8c4fa8d605505a85fae4c692066ac0375cf6).

**Pull request merged**
